# name: Update Development Tracking Plan

# on:
#   push:
#     branches-ignore:
#       - main
#     paths:
#       - 'tracking-rules/**.yml'

# jobs:
#   update-tracking-plan:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '14'

#     - name: Install dependencies
#       run: npm install

#     - name: Run update script
#       env:
#         SEGMENT_PUBLIC_API_TOKEN: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}
#         SEGMENT_WORKSPACE_SLUG: ${{ secrets.SEGMENT_WORKSPACE_SLUG }}
#         SEGMENT_TRACKING_PLAN_ID: ${{ secrets.SEGMENT_TRACKING_PLAN_ID }}
#       run: node scripts/update-tracking-plan.js


name: Update Development Tracking Plans

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'tracking-rules/javascript/**.yml'
      - 'tracking-rules/server/**.yml'

jobs:
  identify-changed-plans:
    runs-on: ubuntu-latest
    outputs:
      plans: ${{ steps.set-changed-plans.outputs.changed_plans }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Identify changed tracking plans
      id: set-changed-plans
      run: |
        if [ "$(git rev-parse --is-shallow-repository)" == "true" ]; then
          git fetch --prune --unshallow
        fi
        changed_files=$(git diff --name-only HEAD~1..HEAD)
        changed_plans=$(echo "$changed_files" | grep 'tracking-rules/' | cut -d'/' -f2 | uniq)
        echo "Changed plans: $changed_plans"
        echo "::set-output name=changed_plans::$changed_plans"

  update-tracking-plan:
    needs: identify-changed-plans
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plan: ${{ fromJson(needs.identify-changed-plans.outputs.changed_plans) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set environment variables for development
      run: |
        if [ "${{ matrix.plan }}" == "javascript" ]; then
          echo "SEGMENT_TRACKING_PLAN_ID=${{ secrets.DEV_SEGMENT_TRACKING_PLAN_ID_JAVASCRIPT }}" >> $GITHUB_ENV
        elif [ "${{ matrix.plan }}" == "server" ]; then
          echo "SEGMENT_TRACKING_PLAN_ID=${{ secrets.DEV_SEGMENT_TRACKING_PLAN_ID_SERVER }}" >> $GITHUB_ENV
        fi

    - name: Run update script
      env:
        SEGMENT_API_KEY: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}  # Comm  on API key
        SEGMENT_TRACKING_PLAN_ID: ${{ env.SEGMENT_TRACKING_PLAN_ID }}
        PLAN_DIR: tracking-rules/${{ matrix.plan }}
      run: node scripts/update-tracking-plan.js

    - name: Save updated tracking plan
      env:
        SEGMENT_API_KEY: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}  # Common API key
        SEGMENT_TRACKING_PLAN_ID: ${{ env.SEGMENT_TRACKING_PLAN_ID }}
        PLAN_DIR: tracking-plans/${{ matrix.plan }}
      run: node scripts/save-tracking-plan.js
