name: Update Development Tracking Plan

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'tracking-rules/**.yml'

jobs:
  update-tracking-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      env:
        SEGMENT_PUBLIC_API_TOKEN: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}
        SEGMENT_WORKSPACE_SLUG: ${{ secrets.SEGMENT_WORKSPACE_SLUG }}
        SEGMENT_TRACKING_PLAN_ID: ${{ secrets.SEGMENT_TRACKING_PLAN_ID }}
      run: node scripts/update-tracking-plan.js
